# Generated by Django 5.2 on 2025-11-04 17:39

import apps.entities.models.base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=12)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "traffic_locations",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                ("model", models.CharField(blank=True, max_length=50, null=True)),
                ("resolution", models.CharField(blank=True, max_length=20, null=True)),
                ("fps", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("lanes", models.IntegerField(default=2)),
                ("coversBothDirections", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "currentVideoPath",
                    models.CharField(
                        blank=True,
                        db_column="currentVideoPath",
                        help_text="Ruta del video actualmente asignado a esta cámara",
                        max_length=500,
                        null=True,
                        verbose_name="Current Video Path",
                    ),
                ),
                (
                    "thumbnailPath",
                    models.CharField(
                        blank=True,
                        db_column="thumbnailPath",
                        help_text="Ruta del thumbnail (primer frame del video)",
                        max_length=500,
                        null=True,
                        verbose_name="Video Thumbnail",
                    ),
                ),
                (
                    "locationId",
                    models.ForeignKey(
                        db_column="locationId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="traffic_app.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Camera",
                "verbose_name_plural": "Cameras",
                "db_table": "traffic_cameras",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="TrafficAnalysis",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("videoPath", models.CharField(blank=True, max_length=500, null=True)),
                ("userId", models.IntegerField(blank=True, null=True)),
                ("startedAt", models.DateTimeField()),
                ("endedAt", models.DateTimeField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("totalFrames", models.IntegerField(default=0)),
                ("processedFrames", models.IntegerField(default=0)),
                ("totalVehicles", models.IntegerField(default=0)),
                ("processingDuration", models.IntegerField(default=0)),
                ("totalVehicleCount", models.IntegerField(default=0)),
                (
                    "avgSpeed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("densityLevel", models.CharField(max_length=10)),
                ("isPlaying", models.BooleanField(default=False)),
                ("isPaused", models.BooleanField(default=False)),
                ("currentTimestamp", models.IntegerField(default=0)),
                (
                    "weatherConditions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("analysisData", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=20)),
                ("errorMessage", models.TextField(blank=True, null=True)),
                ("carCount", models.IntegerField(default=0)),
                ("truckCount", models.IntegerField(default=0)),
                ("motorcycleCount", models.IntegerField(default=0)),
                ("busCount", models.IntegerField(default=0)),
                ("bicycleCount", models.IntegerField(default=0)),
                ("otherCount", models.IntegerField(default=0)),
                ("platesDetected", models.IntegerField(default=0)),
                ("platesCaptured", models.IntegerField(default=0)),
                (
                    "cameraId",
                    models.ForeignKey(
                        db_column="cameraId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="traffic_app.camera",
                        verbose_name="Camera",
                    ),
                ),
                (
                    "locationId",
                    models.ForeignKey(
                        db_column="locationId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="traffic_app.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traffic Analysis",
                "verbose_name_plural": "Traffic Analyses",
                "db_table": "traffic_analyses",
                "ordering": ["-startedAt"],
            },
        ),
        migrations.CreateModel(
            name="DetectedPlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Imagen capturada de la placa detectada",
                        upload_to="plates/raw/",
                        verbose_name="Plate Image",
                    ),
                ),
                (
                    "image_processed",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen procesada (mejoras, OCR, etc.) - Opcional",
                        null=True,
                        upload_to="plates/processed/",
                        verbose_name="Processed Image",
                    ),
                ),
                (
                    "frame_number",
                    models.IntegerField(
                        db_column="frameNumber",
                        help_text="Número de frame donde se detectó la placa",
                        verbose_name="Frame Number",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="timestamp",
                        help_text="Momento exacto de la detección",
                        verbose_name="Detection Timestamp",
                    ),
                ),
                (
                    "vehicle_bbox",
                    models.JSONField(
                        db_column="vehicleBbox",
                        help_text="Coordenadas del vehículo [x1, y1, x2, y2] en el frame",
                        verbose_name="Vehicle Bounding Box",
                    ),
                ),
                (
                    "plate_bbox",
                    models.JSONField(
                        db_column="plateBbox",
                        help_text="Coordenadas de la placa [px, py, pw, ph] relativas al vehículo",
                        verbose_name="Plate Bounding Box (Relative)",
                    ),
                ),
                (
                    "plate_bbox_absolute",
                    models.JSONField(
                        db_column="plateBboxAbsolute",
                        help_text="Coordenadas absolutas de la placa [x, y, w, h] en el frame",
                        verbose_name="Plate Bounding Box (Absolute)",
                    ),
                ),
                (
                    "vehicle_confidence",
                    models.FloatField(
                        db_column="vehicleConfidence",
                        help_text="Nivel de confianza de la detección del vehículo (0.0 - 1.0)",
                        verbose_name="Vehicle Detection Confidence",
                    ),
                ),
                (
                    "vehicle_class",
                    models.IntegerField(
                        db_column="vehicleClass",
                        help_text="Clase del vehículo detectado (2=car, 3=motorcycle, 5=bus, 7=truck)",
                        verbose_name="Vehicle Class",
                    ),
                ),
                (
                    "crossed_detection_line",
                    models.BooleanField(
                        db_column="crossedDetectionLine",
                        default=False,
                        help_text="Indica si el vehículo cruzó la línea de detección",
                        verbose_name="Crossed Detection Line",
                    ),
                ),
                (
                    "detection_line_y",
                    models.IntegerField(
                        blank=True,
                        db_column="detectionLineY",
                        help_text="Posición Y de la línea de detección en el frame",
                        null=True,
                        verbose_name="Detection Line Y Position",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        db_column="metadata",
                        default=dict,
                        help_text="Información adicional (dimensiones, calidad, etc.)",
                        verbose_name="Additional Metadata",
                    ),
                ),
                (
                    "cloud_url",
                    models.URLField(
                        blank=True,
                        db_column="cloudUrl",
                        help_text="URL de la imagen en servicio cloud (Firebase, S3, etc.)",
                        max_length=500,
                        null=True,
                        verbose_name="Cloud Storage URL",
                    ),
                ),
                (
                    "cloud_uploaded",
                    models.BooleanField(
                        db_column="cloudUploaded",
                        default=False,
                        help_text="Indica si la imagen fue subida al servicio cloud",
                        verbose_name="Uploaded to Cloud",
                    ),
                ),
                (
                    "cloud_uploaded_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="cloudUploadedAt",
                        help_text="Fecha y hora de subida al cloud",
                        null=True,
                        verbose_name="Cloud Upload Timestamp",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        db_column="analysisId",
                        help_text="Análisis de tráfico al que pertenece esta placa",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_plates",
                        to="traffic_app.trafficanalysis",
                        verbose_name="Traffic Analysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detected Plate",
                "verbose_name_plural": "Detected Plates",
                "db_table": "traffic_detected_plates",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="camera",
            name="currentAnalysisId",
            field=models.ForeignKey(
                blank=True,
                db_column="currentAnalysisId",
                help_text="Análisis activo asociado a esta cámara",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_camera",
                to="traffic_app.trafficanalysis",
                verbose_name="Current Analysis",
            ),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        db_column="id",
                        default=apps.entities.models.base.generate_string_id,
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicleType", models.CharField(max_length=20)),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "detectedPlate",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "plateConfidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("firstDetectedAt", models.DateTimeField()),
                ("lastDetectedAt", models.DateTimeField()),
                ("trackingStatus", models.CharField(max_length=20)),
                (
                    "avgSpeed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("direction", models.CharField(blank=True, max_length=20, null=True)),
                ("lane", models.IntegerField(blank=True, null=True)),
                ("totalFrames", models.IntegerField(default=0)),
                ("storedFrames", models.IntegerField(default=0)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                ("model", models.CharField(blank=True, max_length=50, null=True)),
                ("plateProcessingStatus", models.CharField(max_length=20)),
                ("bestFrameForPlate", models.IntegerField(blank=True, null=True)),
                (
                    "trafficAnalysisId",
                    models.ForeignKey(
                        db_column="trafficAnalysisId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="traffic_app.trafficanalysis",
                        verbose_name="Traffic Analysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "traffic_vehicles",
                "ordering": ["-firstDetectedAt"],
            },
        ),
        migrations.CreateModel(
            name="VehicleFrame",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("frameNumber", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                ("boundingBoxX", models.IntegerField()),
                ("boundingBoxY", models.IntegerField()),
                ("boundingBoxWidth", models.IntegerField()),
                ("boundingBoxHeight", models.IntegerField()),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                ("frameQuality", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("imagePath", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "vehicleId",
                    models.ForeignKey(
                        db_column="vehicleId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="traffic_app.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Frame",
                "verbose_name_plural": "Vehicle Frames",
                "db_table": "traffic_vehicle_frames",
                "ordering": ["frameNumber"],
            },
        ),
        migrations.AddIndex(
            model_name="trafficanalysis",
            index=models.Index(
                fields=["cameraId", "startedAt"], name="traffic_ana_cameraI_99ca1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trafficanalysis",
            index=models.Index(fields=["status"], name="traffic_ana_status_191dc6_idx"),
        ),
        migrations.AddIndex(
            model_name="trafficanalysis",
            index=models.Index(
                fields=["startedAt", "endedAt"], name="traffic_ana_started_0a3f76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectedplate",
            index=models.Index(
                fields=["analysis", "frame_number"],
                name="traffic_det_analysi_81d5b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detectedplate",
            index=models.Index(
                fields=["crossed_detection_line"], name="traffic_det_crossed_113873_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectedplate",
            index=models.Index(
                fields=["cloud_uploaded"], name="traffic_det_cloudUp_5231d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectedplate",
            index=models.Index(
                fields=["timestamp"], name="traffic_det_timesta_633394_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="camera",
            index=models.Index(
                fields=["locationId", "isActive"], name="traffic_cam_locatio_422f72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="camera",
            index=models.Index(fields=["brand"], name="traffic_cam_brand_9b15ac_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["trafficAnalysisId", "vehicleType"],
                name="traffic_veh_traffic_8a1f64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["trackingStatus"], name="traffic_veh_trackin_5b332c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleframe",
            index=models.Index(
                fields=["vehicleId", "frameNumber"],
                name="traffic_veh_vehicle_32e708_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleframe",
            index=models.Index(
                fields=["frameQuality"], name="traffic_veh_frameQu_60dde2_idx"
            ),
        ),
    ]
