# Generated by Django 5.2 on 2025-11-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DetectedPlate",
        ),
    ]
