# Generated by Django 5.2 on 2025-10-09 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="currentLocationId",
            field=models.ForeignKey(
                blank=True,
                db_column="currentLocationId",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_cameras",
                to="traffic_app.location",
                verbose_name="Current Location",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="locationId",
            field=models.ForeignKey(
                db_column="locationId",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cameras",
                to="traffic_app.location",
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="trafficanalysis",
            name="cameraId",
            field=models.ForeignKey(
                db_column="cameraId",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="traffic_app.camera",
                verbose_name="Camera",
            ),
        ),
        migrations.AlterField(
            model_name="trafficanalysis",
            name="locationId",
            field=models.ForeignKey(
                db_column="locationId",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="traffic_app.location",
                verbose_name="Location",
            ),
        ),
    ]
