# Generated by Django 5.2 on 2025-10-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
