# Generated by Django 5.2 on 2025-10-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficanalysis",
            name="currentTimestamp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trafficanalysis",
            name="isPaused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trafficanalysis",
            name="isPlaying",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="detectedPlate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="plateConfidence",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=5, null=True
            ),
        ),
    ]
