# Generated by Django 5.2 on 2025-11-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_app", "0002_delete_detectedplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("MAINTENANCE", "Maintenance"),
                ],
                db_column="status",
                default="ACTIVE",
                max_length=20,
                verbose_name="Camera Status",
            ),
        ),
        migrations.AlterField(
            model_name="trafficanalysis",
            name="densityLevel",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("HEAVY", "Heavy"),
                ],
                db_column="densityLevel",
                max_length=10,
                verbose_name="Density Level",
            ),
        ),
        migrations.AlterField(
            model_name="trafficanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_column="status",
                max_length=20,
                verbose_name="Analysis Status",
            ),
        ),
    ]
