# Generated by Django 5.2 on 2025-10-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_app", "0002_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
