# Generated by Django 5.2 on 2025-10-13 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_app", "0002_trafficanalysis_currenttimestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="currentAnalysisId",
            field=models.ForeignKey(
                blank=True,
                db_column="currentAnalysisId",
                help_text="Análisis activo asociado a esta cámara",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_camera",
                to="traffic_app.trafficanalysis",
                verbose_name="Current Analysis",
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="currentVideoPath",
            field=models.CharField(
                blank=True,
                db_column="currentVideoPath",
                help_text="Ruta del video actualmente asignado a esta cámara",
                max_length=500,
                null=True,
                verbose_name="Current Video Path",
            ),
        ),
    ]
