# Generated by Django 5.2 on 2025-10-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_app", "0003_camera_currentanalysisid_camera_currentvideopath"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="thumbnailPath",
            field=models.CharField(
                blank=True,
                db_column="thumbnailPath",
                help_text="Ruta del thumbnail (primer frame del video)",
                max_length=500,
                null=True,
                verbose_name="Video Thumbnail",
            ),
        ),
    ]
