# Generated by Django 5.2 on 2025-11-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_app", "0003_alter_camera_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("MAINTENANCE", "Maintenance"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trafficanalysis",
            name="densityLevel",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("HEAVY", "Heavy"),
                ],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="trafficanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NORTH", "North"),
                    ("SOUTH", "South"),
                    ("EAST", "East"),
                    ("WEST", "West"),
                    ("NORTHEAST", "Northeast"),
                    ("NORTHWEST", "Northwest"),
                    ("SOUTHEAST", "Southeast"),
                    ("SOUTHWEST", "Southwest"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="plateProcessingStatus",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("DETECTED", "Detected"),
                    ("NOT_DETECTED", "Not Detected"),
                    ("FAILED", "Failed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="trackingStatus",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("EXITED", "Exited"), ("LOST", "Lost")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicleType",
            field=models.CharField(
                choices=[
                    ("CAR", "Car"),
                    ("TRUCK", "Truck"),
                    ("MOTORCYCLE", "Motorcycle"),
                    ("BUS", "Bus"),
                    ("BICYCLE", "Bicycle"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
