# Generated by Django 5.2 on 2025-11-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_app", "0004_add_thumbnail_path"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["firstDetectedAt"], name="traffic_veh_firstDe_8dff5d_idx"
            ),
        ),
    ]
