# Generated by Django 5.2.7 on 2025-11-03 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_app", "0004_add_thumbnail_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficanalysis",
            name="plates_captured",
            field=models.IntegerField(
                db_column="platesCaptured",
                default=0,
                help_text="Total de placas capturadas y guardadas",
                verbose_name="Plates Captured",
            ),
        ),
        migrations.AddField(
            model_name="trafficanalysis",
            name="plates_detected",
            field=models.IntegerField(
                db_column="platesDetected",
                default=0,
                help_text="Total de placas detectadas en el análisis",
                verbose_name="Plates Detected",
            ),
        ),
        migrations.CreateModel(
            name="DetectedPlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Imagen capturada de la placa detectada",
                        upload_to="plates/raw/",
                        verbose_name="Plate Image",
                    ),
                ),
                (
                    "image_processed",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen procesada (mejoras, OCR, etc.) - Opcional",
                        null=True,
                        upload_to="plates/processed/",
                        verbose_name="Processed Image",
                    ),
                ),
                (
                    "frame_number",
                    models.IntegerField(
                        db_column="frameNumber",
                        help_text="Número de frame donde se detectó la placa",
                        verbose_name="Frame Number",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="timestamp",
                        help_text="Momento exacto de la detección",
                        verbose_name="Detection Timestamp",
                    ),
                ),
                (
                    "vehicle_bbox",
                    models.JSONField(
                        db_column="vehicleBbox",
                        help_text="Coordenadas del vehículo [x1, y1, x2, y2] en el frame",
                        verbose_name="Vehicle Bounding Box",
                    ),
                ),
                (
                    "plate_bbox",
                    models.JSONField(
                        db_column="plateBbox",
                        help_text="Coordenadas de la placa [px, py, pw, ph] relativas al vehículo",
                        verbose_name="Plate Bounding Box (Relative)",
                    ),
                ),
                (
                    "plate_bbox_absolute",
                    models.JSONField(
                        db_column="plateBboxAbsolute",
                        help_text="Coordenadas absolutas de la placa [x, y, w, h] en el frame",
                        verbose_name="Plate Bounding Box (Absolute)",
                    ),
                ),
                (
                    "vehicle_confidence",
                    models.FloatField(
                        db_column="vehicleConfidence",
                        help_text="Nivel de confianza de la detección del vehículo (0.0 - 1.0)",
                        verbose_name="Vehicle Detection Confidence",
                    ),
                ),
                (
                    "vehicle_class",
                    models.IntegerField(
                        db_column="vehicleClass",
                        help_text="Clase del vehículo detectado (2=car, 3=motorcycle, 5=bus, 7=truck)",
                        verbose_name="Vehicle Class",
                    ),
                ),
                (
                    "crossed_detection_line",
                    models.BooleanField(
                        db_column="crossedDetectionLine",
                        default=False,
                        help_text="Indica si el vehículo cruzó la línea de detección",
                        verbose_name="Crossed Detection Line",
                    ),
                ),
                (
                    "detection_line_y",
                    models.IntegerField(
                        blank=True,
                        db_column="detectionLineY",
                        help_text="Posición Y de la línea de detección en el frame",
                        null=True,
                        verbose_name="Detection Line Y Position",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        db_column="metadata",
                        default=dict,
                        help_text="Información adicional (dimensiones, calidad, etc.)",
                        verbose_name="Additional Metadata",
                    ),
                ),
                (
                    "cloud_url",
                    models.URLField(
                        blank=True,
                        db_column="cloudUrl",
                        help_text="URL de la imagen en servicio cloud (Firebase, S3, etc.)",
                        max_length=500,
                        null=True,
                        verbose_name="Cloud Storage URL",
                    ),
                ),
                (
                    "cloud_uploaded",
                    models.BooleanField(
                        db_column="cloudUploaded",
                        default=False,
                        help_text="Indica si la imagen fue subida al servicio cloud",
                        verbose_name="Uploaded to Cloud",
                    ),
                ),
                (
                    "cloud_uploaded_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="cloudUploadedAt",
                        help_text="Fecha y hora de subida al cloud",
                        null=True,
                        verbose_name="Cloud Upload Timestamp",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        db_column="analysisId",
                        help_text="Análisis de tráfico al que pertenece esta placa",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_plates",
                        to="traffic_app.trafficanalysis",
                        verbose_name="Traffic Analysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detected Plate",
                "verbose_name_plural": "Detected Plates",
                "db_table": "traffic_detected_plates",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["analysis", "frame_number"],
                        name="traffic_det_analysi_81d5b0_idx",
                    ),
                    models.Index(
                        fields=["crossed_detection_line"],
                        name="traffic_det_crossed_113873_idx",
                    ),
                    models.Index(
                        fields=["cloud_uploaded"], name="traffic_det_cloudUp_5231d6_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="traffic_det_timesta_633394_idx"
                    ),
                ],
            },
        ),
    ]
