# Generated by Django 5.2 on 2025-10-10 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("passwordHash", models.CharField(max_length=255)),
                ("firstName", models.CharField(max_length=255)),
                ("lastName", models.CharField(max_length=255)),
                (
                    "phoneNumber",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "profileImage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("emailConfirmed", models.BooleanField(default=False)),
                (
                    "lastLogin",
                    models.DateTimeField(blank=True, db_column="lastLogin", null=True),
                ),
                (
                    "failedLoginAttempts",
                    models.IntegerField(db_column="failedLoginAttempts", default=0),
                ),
                (
                    "isLockedOut",
                    models.BooleanField(db_column="isLockedOut", default=False),
                ),
                (
                    "lockoutUntil",
                    models.DateTimeField(
                        blank=True, db_column="lockoutUntil", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "auth_users",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=100, unique=True)),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                ("expiresAt", models.DateTimeField(db_column="expiresAt")),
                ("isUsed", models.BooleanField(db_column="isUsed", default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_tokens",
                        to="auth_app.user",
                    ),
                ),
            ],
            options={
                "db_table": "auth_password_reset_tokens",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="LoginSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sessionKey",
                    models.CharField(
                        db_column="sessionKey", max_length=40, unique=True
                    ),
                ),
                ("ipAddress", models.GenericIPAddressField(db_column="ipAddress")),
                ("userAgent", models.TextField(db_column="userAgent")),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                ("expiresAt", models.DateTimeField(db_column="expiresAt")),
                ("isActive", models.BooleanField(db_column="isActive", default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="auth_app.user",
                    ),
                ),
            ],
            options={
                "db_table": "auth_login_sessions",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="EmailConfirmationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=100, unique=True)),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                ("expiresAt", models.DateTimeField(db_column="expiresAt")),
                ("isUsed", models.BooleanField(db_column="isUsed", default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmation_tokens",
                        to="auth_app.user",
                    ),
                ),
            ],
            options={
                "db_table": "auth_email_confirmation_tokens",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                ("userId", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("OPERATOR", "Operator"),
                            ("VIEWER", "Viewer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("assignedBy", models.CharField(blank=True, max_length=255, null=True)),
                ("assignedAt", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="auth_app.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "auth_user_roles",
                "unique_together": {("user", "role")},
            },
        ),
    ]
