# Generated by Django 5.2 on 2025-09-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="assignedAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
