# Generated by Django 5.2 on 2025-11-11 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("OPERATOR", "Operator"),
                    ("VIEWER", "Viewer"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userRoles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
