# Generated by Django 5.2 on 2025-10-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_alter_user_emailconfirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profileImage",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
