# Generated by Django 5.2 on 2025-11-11 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_alter_userrole_role_alter_userrole_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="assignedAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("OPERATOR", "Operator"),
                            ("VIEWER", "Viewer"),
                        ],
                        db_column="role",
                        max_length=20,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        db_column="permission",
                        help_text="Format: 'module:action' (e.g., 'traffic:create', 'users:delete')",
                        max_length=100,
                    ),
                ),
                (
                    "isGranted",
                    models.BooleanField(
                        db_column="isGranted",
                        default=True,
                        help_text="True=grant permission, False=revoke permission",
                    ),
                ),
                (
                    "grantedAt",
                    models.DateTimeField(auto_now_add=True, db_column="grantedAt"),
                ),
                (
                    "expiresAt",
                    models.DateTimeField(
                        blank=True,
                        db_column="expiresAt",
                        help_text="Optional: permission expires after this date",
                        null=True,
                    ),
                ),
                (
                    "grantedBy",
                    models.ForeignKey(
                        blank=True,
                        db_column="grantedBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_role_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_role_permissions",
                "ordering": ["role", "permission"],
                "indexes": [
                    models.Index(
                        fields=["role", "permission"],
                        name="auth_role_p_role_841339_idx",
                    ),
                    models.Index(
                        fields=["expiresAt"], name="auth_role_p_expires_74b8a1_idx"
                    ),
                ],
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.CreateModel(
            name="UserPermissionOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        db_column="permission",
                        help_text="Format: 'module:action' (e.g., 'traffic:create', 'users:delete')",
                        max_length=100,
                    ),
                ),
                (
                    "isGranted",
                    models.BooleanField(
                        db_column="isGranted",
                        help_text="True=grant permission, False=revoke permission",
                    ),
                ),
                (
                    "overrideReason",
                    models.TextField(
                        blank=True,
                        db_column="overrideReason",
                        help_text="Reason for granting/revoking this specific permission",
                        null=True,
                    ),
                ),
                (
                    "grantedAt",
                    models.DateTimeField(auto_now_add=True, db_column="grantedAt"),
                ),
                (
                    "expiresAt",
                    models.DateTimeField(
                        blank=True,
                        db_column="expiresAt",
                        help_text="Optional: override expires after this date",
                        null=True,
                    ),
                ),
                (
                    "grantedBy",
                    models.ForeignKey(
                        blank=True,
                        db_column="grantedBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_user_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_permission_overrides",
                "ordering": ["user", "permission"],
                "indexes": [
                    models.Index(
                        fields=["user", "permission"],
                        name="auth_user_p_userId_4065fb_idx",
                    ),
                    models.Index(
                        fields=["expiresAt"], name="auth_user_p_expires_865fa7_idx"
                    ),
                ],
                "unique_together": {("user", "permission")},
            },
        ),
    ]
