# Generated by Django 5.2 on 2025-11-12 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("traffic_app", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectedPlate",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("plateNumber", models.CharField(max_length=20)),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                ("detectionMethod", models.CharField(max_length=50)),
                ("frameNumber", models.IntegerField()),
                ("frameQuality", models.DecimalField(decimal_places=4, max_digits=5)),
                ("detectedAt", models.DateTimeField()),
                ("wasCheckedForComplaints", models.BooleanField(default=False)),
                ("checkedAt", models.DateTimeField(blank=True, null=True)),
                ("hasComplaints", models.BooleanField(default=False)),
                (
                    "trafficAnalysisId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detectedplateentity_trafficanalysis_set",
                        to="traffic_app.trafficanalysis",
                    ),
                ),
                (
                    "vehicleId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detectedplateentity_vehicle_set",
                        to="traffic_app.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "DetectedPlate",
                "verbose_name_plural": "DetectedPlates",
                "db_table": "detected_plates",
            },
        ),
        migrations.CreateModel(
            name="DetectedPlateImage",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("localImagePath", models.CharField(max_length=500)),
                ("imageType", models.CharField(max_length=20)),
                ("frameNumber", models.IntegerField()),
                ("capturedAt", models.DateTimeField()),
                ("fileSize", models.IntegerField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "detectedPlateId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detectedplateimageentity_detectedplate_set",
                        to="plates_app.detectedplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "DetectedPlateImage",
                "verbose_name_plural": "DetectedPlateImages",
                "db_table": "detected_plate_images",
            },
        ),
        migrations.CreateModel(
            name="VehicleComplaintDetection",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ownerName", models.CharField(max_length=200)),
                ("ownerIdNumber", models.CharField(max_length=32)),
                ("ownerAddress", models.CharField(max_length=400)),
                ("caseNumber", models.CharField(max_length=64)),
                ("totalComplaintsCount", models.IntegerField(default=0)),
                ("severity", models.CharField(blank=True, max_length=20, null=True)),
                ("wasNotified", models.BooleanField(default=False)),
                ("notifiedAt", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "detectedPlateId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiclecomplaintdetectionentity_detectedplate_set",
                        to="plates_app.detectedplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "VehicleComplaintDetection",
                "verbose_name_plural": "VehicleComplaintDetections",
                "db_table": "vehicle_complaint_detections",
            },
        ),
        migrations.CreateModel(
            name="VehicleComplaint",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("complaintText", models.TextField()),
                (
                    "complaintType",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("complaintDate", models.DateTimeField(blank=True, null=True)),
                ("severity", models.CharField(blank=True, max_length=20, null=True)),
                ("sequenceNumber", models.IntegerField(default=1)),
                (
                    "detectionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiclecomplaintentity_detection_set",
                        to="plates_app.vehiclecomplaintdetection",
                    ),
                ),
            ],
            options={
                "verbose_name": "VehicleComplaint",
                "verbose_name_plural": "VehicleComplaints",
                "db_table": "vehicle_complaints",
            },
        ),
        migrations.CreateModel(
            name="ComplaintEvidenceImage",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cloudUrl", models.CharField(max_length=500)),
                ("cloudBlobName", models.CharField(max_length=200)),
                ("cloudContainerName", models.CharField(max_length=100)),
                ("uploadedAt", models.DateTimeField()),
                ("uploadStatus", models.CharField(max_length=20)),
                ("uploadError", models.TextField(blank=True, null=True)),
                ("cloudFileSize", models.IntegerField(blank=True, null=True)),
                ("expiresAt", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "detectedPlateImageId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaintevidenceimageentity_detectedplateimage_set",
                        to="plates_app.detectedplateimage",
                    ),
                ),
                (
                    "complaintDetectionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaintevidenceimageentity_complaintdetection_set",
                        to="plates_app.vehiclecomplaintdetection",
                    ),
                ),
            ],
            options={
                "verbose_name": "ComplaintEvidenceImage",
                "verbose_name_plural": "ComplaintEvidenceImages",
                "db_table": "complaint_evidence_images",
            },
        ),
    ]
