# Generated by Django 5.2 on 2025-11-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plates_app", "0002_complaintevidenceimage_detectedplate_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="complaintevidenceimage",
            table="complaint_evidence_images",
        ),
        migrations.AlterModelTable(
            name="detectedplate",
            table="detected_plates",
        ),
        migrations.AlterModelTable(
            name="vehiclecomplaint",
            table="vehicle_complaints",
        ),
        migrations.AlterModelTable(
            name="vehiclecomplaintdetection",
            table="vehicle_complaint_detections",
        ),
    ]
