# Generated by Django 5.2 on 2025-11-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plates_app", "0003_alter_complaintevidenceimage_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="detectedplateimage",
            table="detected_plate_images",
        ),
    ]
