# Generated by Django 5.2 on 2025-11-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plates_app", "0004_alter_detectedplateimage_table"),
        ("traffic_app", "0002_delete_detectedplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectedplate",
            name="vehicleId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detectedplateentity_vehicle_set",
                to="traffic_app.vehicle",
            ),
        ),
    ]
