"""
ENTITIES CONSTANTS - Organized by Category
Auto-generated from TypeScript types
"""

# Common Constants
from .common import (
    API_ENDPOINTS,
    API_ENDPOINTS_CHOICES,
    DataTypeKey,
    DataTypeKey_CHOICES,
    FILE_UPLOAD,
    FILE_UPLOAD_CHOICES,
    GroupByDataKey,
    GroupByDataKey_CHOICES,
    PAGINATION,
    PAGINATION_CHOICES,
    SYSTEM_LIMITS,
    SYSTEM_LIMITS_CHOICES,
    TIME,
    TIME_CHOICES,
)

# Notifications Constants
from .notifications import (
    NOTIFICATION_TYPES,
    NOTIFICATION_TYPES_CHOICES,
    NotificationType,
    NotificationType_CHOICES,
)

# Roles Constants
from .roles import (
    PERMISSIONS,
    PERMISSIONS_CHOICES,
    ROLE_PERMISSIONS,
    ROLE_PERMISSIONS_CHOICES,
    USER_ROLES,
    USER_ROLES_CHOICES,
)

# Traffic Constants
from .traffic import (
    ALERT_TYPE,
    ALERT_TYPE_CHOICES,
    ANALYSIS_STATUS,
    ANALYSIS_STATUS_CHOICES,
    DENSITY_LEVELS,
    DENSITY_LEVELS_CHOICES,
    PLATE_PROCESSING_STATUS,
    PLATE_PROCESSING_STATUS_CHOICES,
    TRACKING_STATUS,
    TRACKING_STATUS_CHOICES,
    TRAFFIC_DIRECTION,
    TRAFFIC_DIRECTION_CHOICES,
    VEHICLE_TYPES,
    VEHICLE_TYPES_CHOICES,
)

__all__ = [
    "ALERT_TYPE",
    "ALERT_TYPE_CHOICES",
    "ANALYSIS_STATUS",
    "ANALYSIS_STATUS_CHOICES",
    "API_ENDPOINTS",
    "API_ENDPOINTS_CHOICES",
    "DENSITY_LEVELS",
    "DENSITY_LEVELS_CHOICES",
    "DataTypeKey",
    "DataTypeKey_CHOICES",
    "FILE_UPLOAD",
    "FILE_UPLOAD_CHOICES",
    "GroupByDataKey",
    "GroupByDataKey_CHOICES",
    "NOTIFICATION_TYPES",
    "NOTIFICATION_TYPES_CHOICES",
    "NotificationType",
    "NotificationType_CHOICES",
    "PAGINATION",
    "PAGINATION_CHOICES",
    "PERMISSIONS",
    "PERMISSIONS_CHOICES",
    "PLATE_PROCESSING_STATUS",
    "PLATE_PROCESSING_STATUS_CHOICES",
    "ROLE_PERMISSIONS",
    "ROLE_PERMISSIONS_CHOICES",
    "SYSTEM_LIMITS",
    "SYSTEM_LIMITS_CHOICES",
    "TIME",
    "TIME_CHOICES",
    "TRACKING_STATUS",
    "TRACKING_STATUS_CHOICES",
    "TRAFFIC_DIRECTION",
    "TRAFFIC_DIRECTION_CHOICES",
    "USER_ROLES",
    "USER_ROLES_CHOICES",
    "VEHICLE_TYPES",
    "VEHICLE_TYPES_CHOICES",
]