# Generated by Django 5.2 on 2025-10-18 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FCMDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="FCM device token", max_length=255, unique=True
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional device name (e.g., 'Juan's iPhone')",
                        max_length=100,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="Device type (e.g., 'ios', 'android', 'web')",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this device is active for notifications",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this token was used for a notification",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FCM Device",
                "verbose_name_plural": "FCM Devices",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="notificatio_user_id_0d0034_idx",
                    ),
                    models.Index(fields=["token"], name="notificatio_token_f45a03_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("stolen_vehicle", "Vehículo Robado"),
                            ("traffic_violation", "Infracción de Tránsito"),
                            ("system_alert", "Alerta del Sistema"),
                            ("test", "Notificación de Prueba"),
                        ],
                        help_text="Type of notification sent",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                ("body", models.TextField(help_text="Notification body content")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        help_text="Additional data sent with notification",
                        null=True,
                    ),
                ),
                (
                    "fcm_response",
                    models.JSONField(
                        blank=True, help_text="FCM API response", null=True
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification was sent successfully",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who received the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "notification_type"],
                        name="notificatio_user_id_ae49d9_idx",
                    ),
                    models.Index(
                        fields=["sent_at"], name="notificatio_sent_at_ecc7f6_idx"
                    ),
                ],
            },
        ),
    ]
