# Generated by Django 5.2 on 2025-11-12 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("traffic_app", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationBottleNeck",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "cameraId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_cameraid_camera_set",
                        to="traffic_app.camera",
                    ),
                ),
                (
                    "locationId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_locationid_location_set",
                        to="traffic_app.location",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_userid_user_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abstract NotificationBottleNeckEntity",
                "verbose_name_plural": "Abstract NotificationBottleNeckEntitys",
            },
        ),
        migrations.CreateModel(
            name="NotificationBottleNeckLog",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sentAt", models.DateTimeField()),
                ("message", models.TextField()),
                ("wasSuccessful", models.BooleanField(default=True)),
                (
                    "notificationBottleNeckId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificationbottleneckid_notificationbottleneck_set",
                        to="notifications_app.notificationbottleneck",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abstract NotificationBottleNeckLogEntity",
                "verbose_name_plural": "Abstract NotificationBottleNeckLogEntitys",
            },
        ),
        migrations.CreateModel(
            name="FCMDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="FCM device token", max_length=255, unique=True
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional device name (e.g., 'Juan's iPhone')",
                        max_length=100,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="Device type (e.g., 'ios', 'android', 'web')",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this device is active for notifications",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this token was used for a notification",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FCM Device",
                "verbose_name_plural": "FCM Devices",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="notificatio_user_id_0d0034_idx",
                    ),
                    models.Index(fields=["token"], name="notificatio_token_f45a03_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                ("body", models.TextField(help_text="Notification body content")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        help_text="Additional data sent with notification",
                        null=True,
                    ),
                ),
                (
                    "fcm_response",
                    models.JSONField(
                        blank=True, help_text="FCM API response", null=True
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification was sent successfully",
                    ),
                ),
                (
                    "notificationType",
                    models.CharField(
                        choices=[
                            ("TRAFFIC_ALERT", "Traffic Alert"),
                            ("TRAFFIC_VIOLATION", "Traffic Violation"),
                            ("STOLEN_VEHICLE", "Stolen Vehicle"),
                            ("VEHICLE_COMPLAINT", "Vehicle Complaint"),
                            ("PLATE_DETECTION", "Plate Detection"),
                            ("SYSTEM_ALERT", "System Alert"),
                            ("USER_ACTION", "User Action"),
                            ("ANALYSIS_COMPLETE", "Analysis Complete"),
                            ("ERROR_NOTIFICATION", "Error Notification"),
                        ],
                        db_column="notification_type",
                        default="SYSTEM_ALERT",
                        max_length=50,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who received the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "notificationType"],
                        name="notificatio_user_id_ae49d9_idx",
                    ),
                    models.Index(
                        fields=["sent_at"], name="notificatio_sent_at_ecc7f6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationTask",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="createdAt",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", verbose_name="Updated At"
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        db_column="isActive", default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("taskId", models.CharField(max_length=255, unique=True)),
                ("scheduleFor", models.DateTimeField()),
                (
                    "notificationBottleNeckId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificationtaskentity_notificationbottleneck_set",
                        to="notifications_app.notificationbottleneck",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Task",
                "verbose_name_plural": "Notification Tasks",
                "db_table": "notification_tasks",
                "ordering": ["-createdAt"],
                "indexes": [
                    models.Index(
                        fields=["notificationBottleNeckId"],
                        name="notificatio_notific_3adb7c_idx",
                    ),
                    models.Index(
                        fields=["isActive"], name="notificatio_isActiv_2934d2_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("taskId",), name="unique_task_id_notification_task"
                    )
                ],
            },
        ),
    ]
