# Generated by Django 5.2 on 2025-10-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "placa",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("propietario_nombre", models.CharField(max_length=200)),
                ("propietario_cedula", models.CharField(max_length=32)),
                ("ubicacion_direccion", models.CharField(max_length=400)),
                ("expediente", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denuncia", models.TextField()),
                (
                    "placa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncias",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
    ]
