# Generated by Django 5.2.8 on 2025-11-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_add_nivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denuncia",
            name="nivel",
            field=models.CharField(
                choices=[("low", "low"), ("medium", "medium"), ("high", "high")],
                default="medium",
                max_length=16,
            ),
        ),
    ]
