# Generated by Django 5.2.8 on 2025-11-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_alter_denuncia_nivel"),
        ("vehicles", "0003_rename_nivel_to_severidad"),
    ]

    operations = []
